version: '3.0'
services:
  frontend:
    image: antoniopapa1991/admin-frontend
    ports:
    - 8080:80
    depends_on:
      - backend
    networks:
      - app

  backend:
    container_name: admin_api
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_DATABASE: admin
      DB_USERNAME: root
      DB_PASSWORD: root
    ports:
    - 8000:8000
    volumes:
    - .:/var/www
    command: sh -c "composer install"
    entrypoint: sh -c "php artisan serve --host=0.0.0.0"
    depends_on:
      - db
    networks:
      - app
    links:
      - "db:db"

  db:
    container_name: admin_db
    image: mysql:5.7.34
    environment:
      MYSQL_DATABASE: admin
      MYSQL_ROOT_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - .dbdata:/var/lib/mysql
    ports:
    - 33866:3386
    - 3306:3306
    networks:
      - app

networks:
  app: